// Code generated by sqlc. Manual fallback — network-restricted environment.

package repository

import (
	"context"
)

const getActiveBanners = `-- name: GetActiveBanners :many
SELECT id, image_url, title, link_type, link_id, sort_order
FROM banners
WHERE is_active = true
ORDER BY sort_order ASC
LIMIT $1
`

func (q *Queries) GetActiveBanners(ctx context.Context, limit int32) ([]Banner, error) {
	rows, err := q.db.Query(ctx, getActiveBanners, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Banner
	for rows.Next() {
		var i Banner
		if err := rows.Scan(
			&i.ID,
			&i.ImageUrl,
			&i.Title,
			&i.LinkType,
			&i.LinkID,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
