// Code generated by sqlc. Manual fallback — network-restricted environment.

package repository

import (
	"context"
	"time"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (photographer_id, coser_id, service_id, date, time, status, total_price, remarks, price_mode, price_status, service_name, service_duration)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, photographer_id, coser_id, service_id, date, time, status, total_price, remarks, created_at, updated_at, price_mode, quote_price, price_status, service_name, service_duration
`

type CreateBookingParams struct {
	PhotographerID  int32     `json:"photographer_id"`
	CoserID         int32     `json:"coser_id"`
	ServiceID       int32     `json:"service_id"`
	Date            time.Time `json:"date"`
	Time            string    `json:"time"`
	Status          string    `json:"status"`
	TotalPrice      int32     `json:"total_price"`
	Remarks         *string   `json:"remarks"`
	PriceMode       string    `json:"price_mode"`
	PriceStatus     string    `json:"price_status"`
	ServiceName     *string   `json:"service_name"`
	ServiceDuration *int32    `json:"service_duration"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.PhotographerID,
		arg.CoserID,
		arg.ServiceID,
		arg.Date,
		arg.Time,
		arg.Status,
		arg.TotalPrice,
		arg.Remarks,
		arg.PriceMode,
		arg.PriceStatus,
		arg.ServiceName,
		arg.ServiceDuration,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.PhotographerID,
		&i.CoserID,
		&i.ServiceID,
		&i.Date,
		&i.Time,
		&i.Status,
		&i.TotalPrice,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PriceMode,
		&i.QuotePrice,
		&i.PriceStatus,
		&i.ServiceName,
		&i.ServiceDuration,
	)
	return i, err
}

const getBookingsByUser = `-- name: GetBookingsByUser :many
SELECT id, photographer_id, coser_id, service_id, date, time, status, total_price, remarks, created_at, updated_at, price_mode, quote_price, price_status, service_name, service_duration
FROM bookings
WHERE coser_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetBookingsByUser(ctx context.Context, coserID int32) ([]Booking, error) {
	rows, err := q.db.Query(ctx, getBookingsByUser, coserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.PhotographerID,
			&i.CoserID,
			&i.ServiceID,
			&i.Date,
			&i.Time,
			&i.Status,
			&i.TotalPrice,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PriceMode,
			&i.QuotePrice,
			&i.PriceStatus,
			&i.ServiceName,
			&i.ServiceDuration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, photographer_id, coser_id, service_id, date, time, status, total_price, remarks, created_at, updated_at, price_mode, quote_price, price_status, service_name, service_duration
FROM bookings WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(&i.ID, &i.PhotographerID, &i.CoserID, &i.ServiceID, &i.Date, &i.Time, &i.Status, &i.TotalPrice, &i.Remarks, &i.CreatedAt, &i.UpdatedAt, &i.PriceMode, &i.QuotePrice, &i.PriceStatus, &i.ServiceName, &i.ServiceDuration)
	return i, err
}

const getOccupiedTimes = `-- name: GetOccupiedTimesByPhotographerDate :many
SELECT time FROM bookings
WHERE photographer_id = $1 AND date = $2 AND status <> 'cancelled'
`

func (q *Queries) GetOccupiedTimesByPhotographerDate(ctx context.Context, photographerID int32, date time.Time) ([]string, error) {
	rows, err := q.db.Query(ctx, getOccupiedTimes, photographerID, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var times []string
	for rows.Next() {
		var t string
		if err := rows.Scan(&t); err != nil {
			return nil, err
		}
		times = append(times, t)
	}
	return times, rows.Err()
}

const countConflict = `-- name: CountConflictBookings :one
SELECT COUNT(*) FROM bookings
WHERE photographer_id = $1 AND date = $2 AND time = $3 AND status <> 'cancelled'
`

func (q *Queries) CountConflictBookings(ctx context.Context, photographerID int32, date time.Time, timeStr string) (int64, error) {
	var n int64
	err := q.db.QueryRow(ctx, countConflict, photographerID, date, timeStr).Scan(&n)
	return n, err
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, photographer_id, coser_id, service_id, date, time, status, total_price, remarks, created_at, updated_at, price_mode, quote_price, price_status, service_name, service_duration
`

func (q *Queries) UpdateBookingStatus(ctx context.Context, id int64, status string) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingStatus, id, status)
	var i Booking
	err := row.Scan(&i.ID, &i.PhotographerID, &i.CoserID, &i.ServiceID, &i.Date, &i.Time, &i.Status, &i.TotalPrice, &i.Remarks, &i.CreatedAt, &i.UpdatedAt, &i.PriceMode, &i.QuotePrice, &i.PriceStatus, &i.ServiceName, &i.ServiceDuration)
	return i, err
}

const getBookingsByUserWithDetails = `-- name: GetBookingsByUserWithDetails :many
SELECT b.id, b.photographer_id, b.coser_id, b.service_id, b.date, b.time, b.status, b.total_price, b.remarks, b.created_at, b.updated_at, b.price_mode, b.quote_price, b.price_status, b.service_name, b.service_duration,
       p.name AS photographer_name, p.avatar AS photographer_avatar, p.user_id AS photographer_user_id,
       s.name AS service_name, COALESCE(s.price, 0) AS service_price
FROM bookings b
LEFT JOIN photographers p ON p.id = b.photographer_id
LEFT JOIN services s ON s.id = b.service_id
WHERE b.coser_id = $1
ORDER BY b.created_at DESC
`

func (q *Queries) GetBookingsByUserWithDetails(ctx context.Context, coserID int32) ([]BookingWithDetails, error) {
	rows, err := q.db.Query(ctx, getBookingsByUserWithDetails, coserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingWithDetails
	for rows.Next() {
		var i BookingWithDetails
		if err := rows.Scan(&i.ID, &i.PhotographerID, &i.CoserID, &i.ServiceID, &i.Date, &i.Time, &i.Status, &i.TotalPrice, &i.Remarks, &i.CreatedAt, &i.UpdatedAt, &i.PriceMode, &i.QuotePrice, &i.PriceStatus, &i.Booking.ServiceName, &i.ServiceDuration, &i.PhotographerName, &i.PhotographerAvatar, &i.PhotographerUserID, &i.ServiceName, &i.ServicePrice); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

type BookingWithCoser struct {
	Booking
	CoserName   string `json:"coser_name"`
	CoserAvatar string `json:"coser_avatar"`
	CoserPhone  string `json:"coser_phone"`
}

const getBookingsByPhotographer = `-- name: GetBookingsByPhotographer :many
SELECT b.id, b.photographer_id, b.coser_id, b.service_id, b.date, b.time, b.status, b.total_price, b.remarks, b.created_at, b.updated_at, b.price_mode, b.quote_price, b.price_status, b.service_name, b.service_duration,
       COALESCE(u.name, '') AS coser_name, COALESCE(u.avatar, '') AS coser_avatar, COALESCE(u.phone, '') AS coser_phone
FROM bookings b
LEFT JOIN users u ON u.id = b.coser_id
WHERE b.photographer_id = $1
ORDER BY b.created_at DESC
`

func (q *Queries) GetBookingsByPhotographer(ctx context.Context, photographerID int32) ([]BookingWithCoser, error) {
	rows, err := q.db.Query(ctx, getBookingsByPhotographer, photographerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingWithCoser
	for rows.Next() {
		var i BookingWithCoser
		if err := rows.Scan(&i.ID, &i.PhotographerID, &i.CoserID, &i.ServiceID, &i.Date, &i.Time, &i.Status, &i.TotalPrice, &i.Remarks, &i.CreatedAt, &i.UpdatedAt, &i.PriceMode, &i.QuotePrice, &i.PriceStatus, &i.ServiceName, &i.ServiceDuration, &i.CoserName, &i.CoserAvatar, &i.CoserPhone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const quoteBooking = `-- name: QuoteBooking :execrows
UPDATE bookings SET quote_price = $2, price_status = 'quoted', updated_at = NOW()
WHERE id = $1 AND photographer_id = $3 AND price_mode = 'negotiable' AND price_status = 'awaiting_quote'
`

func (q *Queries) QuoteBooking(ctx context.Context, id int64, price int32, photographerID int32) (int64, error) {
	tag, err := q.db.Exec(ctx, quoteBooking, id, price, photographerID)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

const acceptBookingQuote = `-- name: AcceptBookingQuote :execrows
UPDATE bookings SET total_price = quote_price, price_status = 'agreed', status = 'confirmed', updated_at = NOW()
WHERE id = $1 AND coser_id = $2 AND price_status = 'quoted'
`

const rejectBookingQuote = `-- name: RejectBookingQuote :execrows
UPDATE bookings SET price_status = 'rejected', status = 'cancelled', updated_at = NOW()
WHERE id = $1 AND coser_id = $2 AND price_status = 'quoted'
`

func (q *Queries) RespondBookingQuote(ctx context.Context, id int64, coserID int32, accept bool) (int64, error) {
	stmt := rejectBookingQuote
	if accept {
		stmt = acceptBookingQuote
	}
	tag, err := q.db.Exec(ctx, stmt, id, coserID)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}
