// Code generated by sqlc. Manual fallback — network-restricted environment.

package repository

import (
	"context"
	"time"
)

const getUpcomingEvents = `-- name: GetUpcomingEvents :many
SELECT id, allcpp_id, name, location, venue, start_date, end_date, cover_url, tags, type_name, status
FROM comic_events
WHERE status = 'upcoming'
ORDER BY start_date ASC
LIMIT $1
`

func (q *Queries) GetUpcomingEvents(ctx context.Context, limit int32) ([]ComicEvent, error) {
	rows, err := q.db.Query(ctx, getUpcomingEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComicEvent
	for rows.Next() {
		var i ComicEvent
		if err := rows.Scan(
			&i.ID,
			&i.AllcppID,
			&i.Name,
			&i.Location,
			&i.Venue,
			&i.StartDate,
			&i.EndDate,
			&i.CoverUrl,
			&i.Tags,
			&i.TypeName,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByAllcppId = `-- name: GetEventByAllcppId :one
SELECT id, allcpp_id, name, location, venue, start_date, end_date, cover_url, tags, type_name, status
FROM comic_events
WHERE allcpp_id = $1
`

func (q *Queries) GetEventByAllcppId(ctx context.Context, allcppID int32) (ComicEvent, error) {
	row := q.db.QueryRow(ctx, getEventByAllcppId, allcppID)
	var i ComicEvent
	err := row.Scan(
		&i.ID,
		&i.AllcppID,
		&i.Name,
		&i.Location,
		&i.Venue,
		&i.StartDate,
		&i.EndDate,
		&i.CoverUrl,
		&i.Tags,
		&i.TypeName,
		&i.Status,
	)
	return i, err
}

type UpsertEventParams struct {
	AllcppID  int32     `json:"allcpp_id"`
	Name      string    `json:"name"`
	Location  *string   `json:"location"`
	Venue     *string   `json:"venue"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	CoverUrl  *string   `json:"cover_url"`
	Tags      []string  `json:"tags"`
	TypeName  *string   `json:"type_name"`
	Status    string    `json:"status"`
	RawData   []byte    `json:"raw_data"`
}

const upsertEvent = `-- name: UpsertEvent :one
INSERT INTO comic_events (
  allcpp_id, name, location, venue, start_date, end_date, cover_url, tags, type_name, status, raw_data, synced_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW()
)
ON CONFLICT (allcpp_id) DO UPDATE SET
  name = EXCLUDED.name,
  location = EXCLUDED.location,
  venue = EXCLUDED.venue,
  start_date = EXCLUDED.start_date,
  end_date = EXCLUDED.end_date,
  cover_url = EXCLUDED.cover_url,
  tags = EXCLUDED.tags,
  type_name = EXCLUDED.type_name,
  status = EXCLUDED.status,
  raw_data = EXCLUDED.raw_data,
  updated_at = NOW(),
  synced_at = NOW()
RETURNING id, allcpp_id, name
`

type UpsertEventRow struct {
	ID       int64  `json:"id"`
	AllcppID int32  `json:"allcpp_id"`
	Name     string `json:"name"`
}

func (q *Queries) UpsertEvent(ctx context.Context, arg UpsertEventParams) (UpsertEventRow, error) {
	row := q.db.QueryRow(ctx, upsertEvent,
		arg.AllcppID,
		arg.Name,
		arg.Location,
		arg.Venue,
		arg.StartDate,
		arg.EndDate,
		arg.CoverUrl,
		arg.Tags,
		arg.TypeName,
		arg.Status,
		arg.RawData,
	)
	var i UpsertEventRow
	err := row.Scan(&i.ID, &i.AllcppID, &i.Name)
	return i, err
}

type SearchEventsParams struct {
	Query  *string `json:"query"`
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
}

const searchEvents = `-- name: SearchEvents :many
SELECT id, allcpp_id, name, location, venue, start_date, end_date, cover_url, tags, type_name, status
FROM comic_events
WHERE ($1::text IS NULL OR location ILIKE '%' || $1 || '%')
ORDER BY start_date ASC
LIMIT $2 OFFSET $3
`

func (q *Queries) SearchEvents(ctx context.Context, arg SearchEventsParams) ([]ComicEvent, error) {
	rows, err := q.db.Query(ctx, searchEvents, arg.Query, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComicEvent
	for rows.Next() {
		var i ComicEvent
		if err := rows.Scan(
			&i.ID,
			&i.AllcppID,
			&i.Name,
			&i.Location,
			&i.Venue,
			&i.StartDate,
			&i.EndDate,
			&i.CoverUrl,
			&i.Tags,
			&i.TypeName,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
