// Code generated by sqlc. Manual fallback — network-restricted environment.

package repository

import (
	"context"
)

const insertFollow = `-- name: InsertFollow :one
INSERT INTO event_follows (user_id, event_id) VALUES ($1, $2)
ON CONFLICT (user_id, event_id) DO NOTHING
RETURNING id, user_id, event_id, created_at
`

type InsertFollowParams struct {
	UserID  string `json:"user_id"`
	EventID int64  `json:"event_id"`
}

func (q *Queries) InsertFollow(ctx context.Context, arg InsertFollowParams) (FollowRow, error) {
	row := q.db.QueryRow(ctx, insertFollow, arg.UserID, arg.EventID)
	var i FollowRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM event_follows WHERE user_id = $1 AND event_id = $2
`

type DeleteFollowParams struct {
	UserID  string `json:"user_id"`
	EventID int64  `json:"event_id"`
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.db.Exec(ctx, deleteFollow, arg.UserID, arg.EventID)
	return err
}

const listFollows = `-- name: ListFollows :many
SELECT f.id, f.event_id, f.created_at, e.name, e.location, e.venue, e.start_date, e.end_date, e.cover_url, e.status
FROM event_follows f
JOIN comic_events e ON e.id = f.event_id
WHERE f.user_id = $1
ORDER BY e.start_date ASC
`

type ListFollowsParams struct {
	UserID string `json:"user_id"`
}

func (q *Queries) ListFollows(ctx context.Context, arg ListFollowsParams) ([]FollowItemRow, error) {
	rows, err := q.db.Query(ctx, listFollows, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FollowItemRow
	for rows.Next() {
		var i FollowItemRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.CreatedAt,
			&i.Name,
			&i.Location,
			&i.Venue,
			&i.StartDate,
			&i.EndDate,
			&i.CoverUrl,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSubscription = `-- name: InsertSubscription :one
INSERT INTO event_subscriptions (user_id, event_id, template_id) VALUES ($1, $2, $3)
ON CONFLICT (user_id, event_id) DO UPDATE SET template_id = EXCLUDED.template_id, status = 'accepted'
RETURNING id, user_id, event_id, template_id, status
`

type InsertSubscriptionParams struct {
	UserID     string `json:"user_id"`
	EventID    int64  `json:"event_id"`
	TemplateID string `json:"template_id"`
}

func (q *Queries) InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) (SubscriptionRow, error) {
	row := q.db.QueryRow(ctx, insertSubscription, arg.UserID, arg.EventID, arg.TemplateID)
	var i SubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TemplateID,
		&i.Status,
	)
	return i, err
}
