// Code generated by sqlc. Manual fallback — network-restricted environment.

package repository

import (
	"context"
)

const getRecommendedPhotographers = `-- name: GetRecommendedPhotographers :many
SELECT p.id, p.name, p.avatar, p.description, p.location, p.rating, p.review_count, p.order_count,
       array_agg(t.name) AS tags
FROM photographers p
LEFT JOIN photographer_tags pt ON p.id = pt.photographer_id
LEFT JOIN tags t ON pt.tag_id = t.id
GROUP BY p.id
ORDER BY p.rating DESC, p.order_count DESC
LIMIT $1
`

func (q *Queries) GetRecommendedPhotographers(ctx context.Context, limit int32) ([]PhotographerWithTags, error) {
	rows, err := q.db.Query(ctx, getRecommendedPhotographers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhotographerWithTags
	for rows.Next() {
		var i PhotographerWithTags
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Avatar,
			&i.Description,
			&i.Location,
			&i.Rating,
			&i.ReviewCount,
			&i.OrderCount,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhotographerById = `-- name: GetPhotographerById :one
SELECT p.id, p.name, p.avatar, p.description, p.location, p.rating, p.review_count, p.order_count,
       array_agg(DISTINCT t.name) FILTER (WHERE t.name IS NOT NULL) AS tags
FROM photographers p
LEFT JOIN photographer_tags pt ON p.id = pt.photographer_id
LEFT JOIN tags t ON pt.tag_id = t.id
WHERE p.id = $1
GROUP BY p.id
`

func (q *Queries) GetPhotographerById(ctx context.Context, id int32) (PhotographerWithTags, error) {
	row := q.db.QueryRow(ctx, getPhotographerById, id)
	var i PhotographerWithTags
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Description,
		&i.Location,
		&i.Rating,
		&i.ReviewCount,
		&i.OrderCount,
		&i.Tags,
	)
	return i, err
}
