// Code generated by sqlc. Manual fallback — network-restricted environment.

package repository

import (
	"context"
)

// Querier is the interface satisfied by *Queries and *Queries.WithTx(...).
type Querier interface {
	// Events
	GetUpcomingEvents(ctx context.Context, limit int32) ([]ComicEvent, error)
	GetEventByAllcppId(ctx context.Context, allcppID int32) (ComicEvent, error)
	UpsertEvent(ctx context.Context, arg UpsertEventParams) (UpsertEventRow, error)
	SearchEvents(ctx context.Context, arg SearchEventsParams) ([]ComicEvent, error)

	// Banners
	GetActiveBanners(ctx context.Context, limit int32) ([]Banner, error)

	// Photographers
	GetRecommendedPhotographers(ctx context.Context, limit int32) ([]PhotographerWithTags, error)
	GetPhotographerById(ctx context.Context, id int32) (PhotographerWithTags, error)

	// Works
	GetFeaturedWorks(ctx context.Context, limit int32) ([]FeaturedWork, error)
	GetWorksByPhotographer(ctx context.Context, photographerID int32) ([]Work, error)

	// Tags
	GetHotTags(ctx context.Context, limit int32) ([]Tag, error)

	// Services
	GetServices(ctx context.Context) ([]Service, error)

	// Reviews
	GetReviewsByPhotographer(ctx context.Context, photographerID int32) ([]Review, error)
}

// Compile-time check that *Queries implements Querier.
var _ Querier = (*Queries)(nil)
