// Code generated by sqlc. Manual fallback — network-restricted environment.

package repository

import (
	"context"
)

const getReviewsByPhotographer = `-- name: GetReviewsByPhotographer :many
SELECT id, photographer_id, user_id, user_name, user_avatar, rating, content, images, created_at
FROM reviews
WHERE photographer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetReviewsByPhotographer(ctx context.Context, photographerID int32) ([]Review, error) {
	rows, err := q.db.Query(ctx, getReviewsByPhotographer, photographerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.PhotographerID,
			&i.UserID,
			&i.UserName,
			&i.UserAvatar,
			&i.Rating,
			&i.Content,
			&i.Images,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
