// Code generated by sqlc. Manual fallback — network-restricted environment.

package repository

import (
	"context"
)

const getServices = `-- name: GetServices :many
SELECT id, name, price, description, duration
FROM services
ORDER BY price ASC
`

func (q *Queries) GetServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, getServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Description,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceById = `-- name: GetServiceById :one
SELECT id, name, price, description, duration
FROM services
WHERE id = $1
`

func (q *Queries) GetServiceById(ctx context.Context, id int64) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceById, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Description,
		&i.Duration,
	)
	return i, err
}
