// Code generated by sqlc. Manual fallback — network-restricted environment.

package repository

import (
	"context"
)

const blockUser = `-- name: BlockUser :exec
INSERT INTO user_blocks (user_id, blocked_user_id) VALUES ($1, $2)
ON CONFLICT (user_id, blocked_user_id) DO NOTHING
`

func (q *Queries) BlockUser(ctx context.Context, userID, blockedUserID int64) error {
	_, err := q.db.Exec(ctx, blockUser, userID, blockedUserID)
	return err
}

const unblockUser = `-- name: UnblockUser :exec
DELETE FROM user_blocks WHERE user_id = $1 AND blocked_user_id = $2
`

func (q *Queries) UnblockUser(ctx context.Context, userID, blockedUserID int64) error {
	_, err := q.db.Exec(ctx, unblockUser, userID, blockedUserID)
	return err
}

const isBlockedPair = `-- name: IsBlockedPair :one
SELECT EXISTS(
  SELECT 1 FROM user_blocks
  WHERE (user_id = $1 AND blocked_user_id = $2)
     OR (user_id = $2 AND blocked_user_id = $1)
)
`

func (q *Queries) IsBlockedPair(ctx context.Context, userA, userB int64) (bool, error) {
	var blocked bool
	err := q.db.QueryRow(ctx, isBlockedPair, userA, userB).Scan(&blocked)
	return blocked, err
}

const listBlockedIDs = `-- name: ListBlockedIDs :many
SELECT blocked_user_id FROM user_blocks WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListBlockedIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listBlockedIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	ids := make([]int64, 0)
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}
	return ids, rows.Err()
}

const listHiddenUserIDs = `-- name: ListHiddenUserIDs :many
SELECT blocked_user_id AS uid FROM user_blocks WHERE user_id = $1
UNION
SELECT user_id AS uid FROM user_blocks WHERE blocked_user_id = $1
`

func (q *Queries) ListHiddenUserIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listHiddenUserIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	ids := make([]int64, 0)
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}
	return ids, rows.Err()
}

const listBlockedUsers = `-- name: ListBlockedUsers :many
SELECT b.blocked_user_id,
       COALESCE(u.name, '') AS name,
       COALESCE(u.avatar, '') AS avatar,
       b.created_at::text AS created_at
FROM user_blocks b
LEFT JOIN users u ON u.id = b.blocked_user_id
WHERE b.user_id = $1
ORDER BY b.created_at DESC
`

type BlockedUserRow struct {
	UserID    int64  `json:"userId"`
	Name      string `json:"name"`
	Avatar    string `json:"avatar"`
	CreatedAt string `json:"createdAt"`
}

func (q *Queries) ListBlockedUsers(ctx context.Context, userID int64) ([]BlockedUserRow, error) {
	rows, err := q.db.Query(ctx, listBlockedUsers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]BlockedUserRow, 0)
	for rows.Next() {
		var i BlockedUserRow
		if err := rows.Scan(&i.UserID, &i.Name, &i.Avatar, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
