// Code generated by sqlc. Manual fallback — network-restricted environment.

package repository

import (
	"context"
)

const getFeaturedWorks = `-- name: GetFeaturedWorks :many
SELECT w.id, w.photographer_id, w.title, w.images, w.description, w.created_at,
       p.name AS photographer_name
FROM works w
JOIN photographers p ON w.photographer_id = p.id
ORDER BY w.created_at DESC
LIMIT $1
`

func (q *Queries) GetFeaturedWorks(ctx context.Context, limit int32) ([]FeaturedWork, error) {
	rows, err := q.db.Query(ctx, getFeaturedWorks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeaturedWork
	for rows.Next() {
		var i FeaturedWork
		if err := rows.Scan(
			&i.ID,
			&i.PhotographerID,
			&i.Title,
			&i.Images,
			&i.Description,
			&i.CreatedAt,
			&i.PhotographerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorksByPhotographer = `-- name: GetWorksByPhotographer :many
SELECT id, photographer_id, title, images, description, created_at
FROM works
WHERE photographer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetWorksByPhotographer(ctx context.Context, photographerID int32) ([]Work, error) {
	rows, err := q.db.Query(ctx, getWorksByPhotographer, photographerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Work
	for rows.Next() {
		var i Work
		if err := rows.Scan(
			&i.ID,
			&i.PhotographerID,
			&i.Title,
			&i.Images,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
