/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'admin-accounts',
    path: '/admin-accounts',
    component: 'layout.base$view.admin-accounts',
    meta: {
      title: 'admin-accounts',
      i18nKey: 'route.admin-accounts',
      icon: 'mdi:account-cog-outline'
    }
  },
  {
    name: 'audit-log',
    path: '/audit-log',
    component: 'layout.base$view.audit-log',
    meta: {
      title: 'audit-log',
      i18nKey: 'route.audit-log',
      icon: 'mdi:history'
    }
  },
  {
    name: 'banner',
    path: '/banner',
    component: 'layout.base$view.banner',
    meta: {
      title: 'banner',
      i18nKey: 'route.banner',
      icon: 'mdi:image-multiple-outline'
    }
  },
  {
    name: 'certification',
    path: '/certification',
    component: 'layout.base$view.certification',
    meta: {
      title: 'certification',
      i18nKey: 'route.certification',
      icon: 'mdi:star-check-outline'
    }
  },
  {
    name: 'content',
    path: '/content',
    component: 'layout.base$view.content',
    meta: {
      title: 'content',
      i18nKey: 'route.content',
      icon: 'mdi:book-open-page-variant-outline'
    }
  },
  {
    name: 'dashboard',
    path: '/dashboard',
    component: 'layout.base$view.dashboard',
    meta: {
      title: 'dashboard',
      i18nKey: 'route.dashboard',
      icon: 'mdi:monitor-dashboard'
    }
  },
  {
    name: 'event',
    path: '/event',
    component: 'layout.base$view.event',
    meta: {
      title: 'event',
      i18nKey: 'route.event',
      icon: 'mdi:calendar-star'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'notification',
    path: '/notification',
    component: 'layout.base$view.notification',
    meta: {
      title: 'notification',
      i18nKey: 'route.notification',
      icon: 'mdi:bell-outline'
    }
  },
  {
    name: 'order',
    path: '/order',
    component: 'layout.base$view.order',
    meta: {
      title: 'order',
      i18nKey: 'route.order',
      icon: 'mdi:clipboard-list'
    }
  },
  {
    name: 'photographer',
    path: '/photographer',
    component: 'layout.base$view.photographer',
    meta: {
      title: 'photographer',
      i18nKey: 'route.photographer',
      icon: 'mdi:account-check'
    }
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base$view.user',
    meta: {
      title: 'user',
      i18nKey: 'route.user',
      icon: 'mdi:account-group'
    }
  }
];
