ALTER TABLE photographers ADD COLUMN IF NOT EXISTS mode VARCHAR(10) NOT NULL DEFAULT 'free';
ALTER TABLE photographers ADD COLUMN IF NOT EXISTS mutual_intro TEXT;
ALTER TABLE photographers ADD COLUMN IF NOT EXISTS certified BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE photographers ADD COLUMN IF NOT EXISTS activated_at TIMESTAMPTZ;
